name: Soulflix CI

on:
    push:
        branches:
            - develop

jobs:
    build_and_deploy:
        runs-on: macos-12
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Setup Node Environment
              uses: actions/setup-node@v2
              with:
                  node-version: '20.13.1'

            - name: Install Dependencies
              run: npm install

            # Disabling tests until we enter pre-production
            # - name: Run Tests
            # run: npm test

            - name: Build
              run: npm run build

            # Only deploy if the workflow is triggered by a push to the main branch
            - name: Deploy App
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOULFLIX_APP_108 }}
                  channelId: live
                  projectId: soulflix-app-108
